export const categories = [
  { id: 1, title: "Новинки", path: "" },
  { id: 2, title: "Скоро в продаже", path: "" },
  { id: 3, title: "Одежда для сна", path: "" },
  { id: 4, title: "Верхняя одежда", path: "" },
  { id: 5, title: "Одежда для дома", path: "" },
  { id: 6, title: "Нижнее белье", path: "" },
  { id: 7, title: "Жакеты", path: "" },
  { id: 8, title: "Платья", path: "" },
  { id: 9, title: "Абайи", path: "" },
  { id: 10, title: "Рубашки и блузы", path: "" },
  { id: 11, title: "Юбки", path: "" },
  { id: 12, title: "Толстовки", path: "" },
  { id: 13, title: "Топы и боди", path: "" },
  { id: 14, title: "Футболки", path: "" },
  { id: 15, title: "Брюки и шорты", path: "" },
  { id: 16, title: "Вечерняя коллекция ", path: "" },
  { id: 17, title: "Аксессуары", path: "" },
  { id: 18, title: "Сумки", path: "" },
  { id: 19, title: "Буркини", path: "" },
  { id: 20, title: "Скоро закончатся", path: "" },
];
